#!/usr/bin/env bash

# Single main WordPress target (Plesk over SSH).
# Auto-generated by setup.sh on 2026-02-18T23:47:35Z.

TARGET_SSH_HOST="52.24.217.50"
TARGET_SSH_USER="roostergrintemp"
TARGET_SSH_PORT="22"

# SSH private key path (leave empty to use default agent/key).
TARGET_SSH_KEY="${HOME}/.ssh/acf_schema_deploy"

# Plesk PHP path for remote WP-CLI calls.
TARGET_REMOTE_PHP_DIR="/opt/plesk/php/8.3/bin"

# Absolute WordPress root for the target install.
TARGET_WP_ROOT="/var/www/vhosts/roostergrintemplates.com/api-gordon-acf-demo.roostergrintemplates.com"

# Locked remote path that stores ACF JSON.
TARGET_REMOTE_ACF_JSON_PATH="/var/www/vhosts/roostergrintemplates.com/api-gordon-acf-demo.roostergrintemplates.com/wp-content/themes/dist/acf-json"

# Site-specific post-deploy WP-CLI command.
# Safe smoke-test command; switch to "wp acf sync --all" once confirmed.
WPCLI_SYNC_COMMAND="wp option get home"
