name: deploy-acf-schema-main

on:
  push:
    branches:
      - main

jobs:
  push-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write workspace .env
        shell: bash
        run: |
          cat > .env <<'EOF'
          TARGET_BASE_URL="${{ secrets.ACF_SCHEMA_BASE_URL }}"
          WP_API_USER="${{ secrets.ACF_SCHEMA_API_USER }}"
          WP_API_APP_PASSWORD="${{ secrets.ACF_SCHEMA_API_APP_PASSWORD }}"
          ACF_SCHEMA_API_HMAC_SECRET="${{ secrets.ACF_SCHEMA_API_HMAC_SECRET }}"
          TARGET_API_PULL_PATH="/wp-json/acf-schema/v1/pull"
          TARGET_API_PUSH_PATH="/wp-json/acf-schema/v1/push"
          TARGET_API_PUSH_ROUTE="/acf-schema/v1/push"
          TARGET_CURL_TIMEOUT="30"
          EOF
          chmod 600 .env

      - name: Push dry-run
        run: ./scripts/push.sh --schema-repo . --dry-run

      - name: Push apply
        run: ./scripts/push.sh --schema-repo .
